import { describe,it,expect } from 'vitest';
import { createLiveApi, ApiError } from './client';
import { createMockApi } from './mock';
import { blankFacts,detailSchema,extractSchema,guidanceSchema,matchesSchema,questionSchema,schemeListSchema } from './contracts';
import detail from './fixtures/scheme-detail.response.json';
import extraction from './fixtures/profile-extract.response.json';
import guidance from './fixtures/guidance.response.json';
import matches from './fixtures/matches.response.json';
import question from './fixtures/question-next.response.json';
import schemes from './fixtures/schemes-list.response.json';
import { safeOfficialUrl } from '@/components/ui';
describe('contract boundary',()=>{
  it('validates frozen backend fixtures without modifying fields',()=>{expect(detailSchema.parse(detail).id).toBe(detail.id);extractSchema.parse(extraction);guidanceSchema.parse(guidance);matchesSchema.parse(matches);questionSchema.parse(question);schemeListSchema.parse(schemes);});
  it('rejects malformed responses',async()=>{const api=createLiveApi('https://api.test',async()=>new Response('{}'));await expect(api.extract('hello')).rejects.toMatchObject({code:'INVALID_RESPONSE'});});
  it.each([400,422,429,503])('keeps HTTP error status %s and request correlation',async(status)=>{const api=createLiveApi('https://api.test',async()=>new Response(JSON.stringify({error:{code:'FAILED',message:'Check the request',request_id:'r-1'}}),{status}));await expect(api.extract('hello')).rejects.toMatchObject({status,requestId:'r-1'});});
  it('normalizes offline failures',async()=>{await expect(createLiveApi('https://api.test',async()=>{throw new TypeError('offline');}).extract('hello')).rejects.toBeInstanceOf(ApiError);});
  it('uses the agreed session and answer body',async()=>{let sent='';const api=createLiveApi('https://api.test',async(input,init)=>{sent=String(input)+' '+init?.body;return new Response(JSON.stringify({session_id:'10000000-0000-4000-8000-000000000001',facts:blankFacts,requires_rematch:true}));});await api.answer('10000000-0000-4000-8000-000000000001','age',24);expect(sent).toContain('/api/v1/profiles/answers');expect(sent).toContain('"field":"age","value":24');});
  it('plays mock responses and preserves unknown on not sure, without repeated questions',async()=>{const api=createMockApi(0);const s=await api.createSession();await api.answer(s.session_id,'land_registration','not_sure');expect((await api.matches(s.session_id,blankFacts)).results[0].status).toBe('needs_information');expect((await api.nextQuestion(s.session_id,'unused')).question).toBe(null);await api.deleteSession(s.session_id);await expect(api.matches(s.session_id,blankFacts)).rejects.toMatchObject({code:'SESSION_EXPIRED'});});
  it('blocks synthetic, insecure and lookalike source links',()=>{for(const u of ['javascript:alert(1)','http://gov.in','https://gov.in.attacker.com','https://example.invalid/source','https://user:pass@nic.in'])expect(safeOfficialUrl(u)).toBe(null);expect(safeOfficialUrl('https://pmkisan.gov.in/')).toBe('https://pmkisan.gov.in/');});
});
