'use client';
import { useState } from 'react';
import { ArrowRight,ArrowUpRight,ShieldCheck,Sparkles,Check,SlidersHorizontal } from 'lucide-react';
import { Badge,Button,GlassPanel,InlineAlert,Input,TextArea } from '@/components/ui';
import { errorMessage,isMock } from '@/lib/api';
import { useProfile } from './hooks';
import { fields,states } from './types';
import { fieldValue } from './model';
import Link from 'next/link';

export const example='I’m a 24-year-old farmer from Maharashtra helping my family farm 1.5 acres.';
export function ModeNotice(){return isMock?<div className="mode-notice"><span className="mode-dot"/><strong>Mock mode</strong><span>Synthetic contract examples. These are not government scheme recommendations.</span></div>:null;}
export function ProfileComposer(){
  const p=useProfile();const [busy,setBusy]=useState<'extract'|'confirm'|'clear'|null>(null);const [error,setError]=useState('');
  async function run(kind:'extract'|'confirm'|'clear'){setBusy(kind);setError('');try{await p[kind]();}catch(e){setError(errorMessage(e));if(kind==='extract')p.setReviewing(true);}finally{setBusy(null);}}
  return <><ModeNotice/><section className="hero home-hero"><div><p className="eyebrow"><span className="tiny-line"/>Possibilities, made personal</p><h1>Support you didn’t<br/>know you had<span className="green">.</span></h1><p className="hero-copy">A little about you. A clearer view of the support available.<br className="desktop-break"/> Discover schemes, understand the conditions, find your next step.</p></div><div className="hero-side"><ShieldCheck size={22}/><span>Clear conditions.<br/>Sources you can check.</span></div></section>
  <div className="discovery-grid"><GlassPanel className="composer-shell"><div className="section-heading"><h2>Let’s start with you</h2><Badge>01 / YOUR PROFILE</Badge></div><p className="muted composer-description">You don’t need to know a scheme’s name.<br/>Just tell us a little about your situation.</p>
    <form onSubmit={e=>{e.preventDefault();void run('extract');}}><label className="sr-only" htmlFor="profile-text">Tell us about yourself</label><TextArea id="profile-text" maxLength={1000} placeholder="I’m a farmer in Maharashtra looking for support for my family…" value={p.text} onChange={e=>p.setText(e.target.value)} aria-describedby="profile-privacy profile-counter"/>
    <div className="composer-meta"><span className="small muted">Your words are a good starting point.</span><span id="profile-counter" className="small muted">{p.text.length}/1000</span></div>
    <div className="example-row"><Sparkles size={15} aria-hidden="true"/><span>Need a starting point?</span><Button type="button" variant="quiet" onClick={()=>p.setText(example)}>Try an example<ArrowUpRight size={14}/></Button></div>
    {isMock&&<p className="small muted mock-extract-note">Mock extraction always returns the sample farmer profile. Use manual entry for your own details.</p>}
    <Button type="submit" className="wide" busy={busy==='extract'} disabled={!p.text.trim()||busy!==null}>Find my schemes<ArrowRight size={18}/></Button>
    <Button type="button" variant="quiet" className="wide" disabled={busy!==null} onClick={()=>{p.setReviewing(true);setError('');}}>Enter details manually<SlidersHorizontal size={15}/></Button>
    <p id="profile-privacy" className="privacy-note"><ShieldCheck size={15} aria-hidden="true"/>Only share what’s needed. Don’t enter Aadhaar numbers.</p></form>
    {error&&<InlineAlert error>{error}</InlineAlert>}
  </GlassPanel><aside className="path-panel"><div className="path-top"><span className="eyebrow">A little less searching</span><span className="path-symbol" aria-hidden="true">↗</span></div><h2>More clarity.<br/>More possibility.</h2><p>Good support starts with knowing where to look. We’ll help you connect the dots.</p><ol className="path-list"><li><span>01</span><div><h3>Tell your story</h3><p>A few details about your life and needs.</p></div></li><li><span>02</span><div><h3>Understand your options</h3><p>See conditions met and what’s still unknown.</p></div></li><li><span>03</span><div><h3>Take an informed next step</h3><p>Prepare your checklist. Visit the official portal.</p></div></li></ol><div className="path-footer"><Check size={16}/>Your pace. Your decisions.</div></aside></div>
  {p.reviewing&&<section className="panel profile-review" aria-labelledby="review-heading"><div className="section-heading"><div><p className="eyebrow">02 / CHECK YOUR DETAILS</p><h2 id="review-heading" tabIndex={-1}>A quick check before we search</h2></div><Badge tone={p.confirmed?'success':'warning'}>{p.confirmed?'Confirmed by you':'Needs your review'}</Badge></div><p className="muted">Correct anything that doesn’t look right. Blank fields stay unknown; nothing is assumed.</p>
  <form onSubmit={e=>{e.preventDefault();void run('confirm');}}><div className="profile-fields">{fields.map(f=>{const v=p.draft.facts[f.key];const id='fact-'+f.key;return <div className="field" key={f.key}><label htmlFor={id}>{f.label}</label>{f.kind==='state'||f.kind==='choice'||f.kind==='boolean'?<select id={id} className="input" value={v===null?'':typeof v==='boolean'?v?'yes':'no':String(v)} onChange={e=>p.edit(f.key,fieldValue(f.kind,e.target.value))}><option value="">Unknown</option>{f.kind==='state'?states.map(([code,label])=><option key={code} value={code}>{label}</option>):<><option value="yes">Yes</option><option value="no">No</option>{f.kind==='choice'&&<option value="not_sure">Not sure</option>}</>}</select>:<Input id={id} type={f.kind==='number'?'number':'text'} min={f.kind==='number'?0:undefined} max={f.max} maxLength={f.key==='occupation'?120:f.key==='gender'?40:80} step={f.key==='land_area_acres'?'any':1} value={v===null?'':String(v)} placeholder="Unknown" onChange={e=>p.edit(f.key,fieldValue(f.kind,e.target.value))}/>}<span className="field-origin">{p.draft.origins[f.key]==='user'?'Edited or confirmed by you':v===null?'Not provided · stays unknown':'Extracted · please review'}</span></div>;})}</div><div className="review-actions"><Button type="submit" busy={busy==='confirm'} disabled={busy!==null}>{p.confirmed?'Confirm updated details':'Confirm my details'}<ArrowRight size={16}/></Button><Button type="button" variant="quiet" busy={busy==='clear'} disabled={busy!==null} onClick={()=>void run('clear')}>Clear my details</Button></div></form>
  {p.confirmed&&<InlineAlert>Your details are confirmed for this anonymous session. <Link href="/discover#browse" className="text-link">Explore schemes</Link></InlineAlert>}
  </section>}
  <div className="trust-strip"><div><ShieldCheck size={20}/><span><strong>You stay in control</strong><br/>Review and edit every detail.</span></div><div><SlidersHorizontal size={20}/><span><strong>Unknown means unknown</strong><br/>We help you see what’s missing.</span></div><div><ArrowUpRight size={20}/><span><strong>A clear next step</strong><br/>Apply through official channels.</span></div></div></>;
}
